spring.datasource.url=jdbc:postgresql://localhost:5432/persons_finder
spring.datasource.username=persons_finder
spring.datasource.password=persons_finder
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
