CREATE TABLE person (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(128) NOT NULL,
    job_title VARCHAR(128),
    hobbies   VARCHAR(512)
);

CREATE TABLE location (
    person_id BIGINT PRIMARY KEY REFERENCES person (id),
    latitude  DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

-- Bounding-box prefilter for the nearby search
CREATE INDEX idx_location_lat_lon ON location (latitude, longitude);
